# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_oxenvcs_cli_global_optspecs
	string join \n v/verbose h/help V/version
end

function __fish_oxenvcs_cli_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_oxenvcs_cli_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_oxenvcs_cli_using_subcommand
	set -l cmd (__fish_oxenvcs_cli_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -s V -l version -d 'Print version'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "init" -d 'Initialize a new Oxen repository for a Logic Pro project'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "add" -d 'Stage changes to be committed'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "commit" -d 'Create a commit with optional audio metadata'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "log" -d 'Show commit history'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "restore" -d 'Restore project to a previous commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "status" -d 'Show repository status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "show" -d 'Show detailed information about a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "diff" -d 'Show changes between commits or working directory'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "compare" -d 'Compare metadata between two commits'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "search" -d 'Search commit history with advanced filtering'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "lock" -d 'Manage project locks for team collaboration'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "auth" -d 'Authenticate with Oxen Hub for remote collaboration'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "metadata-diff" -d 'Compare metadata between two Logic Pro project versions'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "daemon" -d 'Control the background daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "hooks" -d 'Manage workflow automation hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "console" -d 'Launch interactive console for real-time monitoring'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "activity" -d 'Show recent project activity timeline'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "team" -d 'Show team members and their contributions'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "queue" -d 'Manage offline operation queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "comment" -d 'Manage comments on commits'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "completions" -d 'Generate shell completion scripts'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand init" -l logic -d 'Initialize for Logic Pro project (auto-detect and configure)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand init" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand init" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand add" -s a -l all -d 'Stage all changes in the repository'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand add" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand add" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -s m -l message -d 'Commit message describing the changes' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -l bpm -d 'Beats per minute (tempo) of the project' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -l sample-rate -d 'Sample rate in Hz (e.g., 44100, 48000, 96000)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -l key -d 'Key signature (e.g., \'C Major\', \'A Minor\', \'F# Minor\')' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -l tags -d 'Tags for categorization (comma-separated, e.g., \'mixing,draft\')' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand commit" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -s l -l limit -d 'Maximum number of commits to display' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -l bpm -d 'Filter by BPM (e.g., 120, 128)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -l tag -d 'Filter by tag (e.g., \'mixing\', \'vocals\')' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -l key -d 'Filter by key signature (e.g., \'C Major\')' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -l since -d 'Show commits since date (YYYY-MM-DD)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand log" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand restore" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand restore" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand status" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand show" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand show" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand diff" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand diff" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand compare" -l format -d 'Output format (text, colored, json, compact)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand compare" -l plain -d 'Disable colored output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand compare" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand compare" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand search" -l format -d 'Output format (list, compact, json)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand search" -l ranked -d 'Sort results by relevance score'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand search" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand search" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -f -a "acquire" -d 'Acquire exclusive lock for editing'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -f -a "release" -d 'Release the lock you currently hold'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -f -a "status" -d 'Show current lock status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -f -a "break" -d 'Force break an existing lock (admin only)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and not __fish_seen_subcommand_from acquire release status break help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from acquire" -l timeout -d 'Lock timeout in hours' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from acquire" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from acquire" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from release" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from release" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from break" -l force -d 'Confirm you want to force break the lock'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from break" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from break" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from help" -f -a "acquire" -d 'Acquire exclusive lock for editing'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from help" -f -a "release" -d 'Release the lock you currently hold'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current lock status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from help" -f -a "break" -d 'Force break an existing lock (admin only)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand lock; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -f -a "login" -d 'Login to Oxen Hub with API credentials'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -f -a "logout" -d 'Logout from Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -f -a "status" -d 'Show current authentication status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -f -a "test" -d 'Test authentication with Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and not __fish_seen_subcommand_from login logout status test help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from login" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from logout" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from logout" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from test" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from test" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "login" -d 'Login to Oxen Hub with API credentials'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "logout" -d 'Logout from Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current authentication status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "test" -d 'Test authentication with Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand metadata-diff" -l output -d 'Output format (text or json)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand metadata-diff" -l color -d 'Use colored output (default: auto-detect)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand metadata-diff" -s v -l verbose -d 'Include technical details in output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand metadata-diff" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "status" -d 'Check daemon status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "start" -d 'Start the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "stop" -d 'Stop the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "restart" -d 'Restart the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "logs" -d 'Show daemon logs'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and not __fish_seen_subcommand_from status start stop restart logs help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from start" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from stop" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from restart" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from restart" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from logs" -l lines -d 'Number of log lines to show' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from logs" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from logs" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "status" -d 'Check daemon status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "start" -d 'Start the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "stop" -d 'Stop the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "restart" -d 'Restart the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "logs" -d 'Show daemon logs'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "init" -d 'Initialize hooks directory'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "list" -d 'List all installed hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "builtins" -d 'List available built-in hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "install" -d 'Install a built-in hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "remove" -d 'Remove an installed hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and not __fish_seen_subcommand_from init list builtins install remove help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from init" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from builtins" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from builtins" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from install" -l hook-type -d 'Hook type (pre-commit or post-commit)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from install" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from remove" -l hook-type -d 'Hook type (pre-commit or post-commit)' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from remove" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize hooks directory'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all installed hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "builtins" -d 'List available built-in hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install a built-in hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove an installed hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand console" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand console" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand activity" -l limit -d 'Number of activities to show' -r
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand activity" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand activity" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand team" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand team" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -f -a "status" -d 'Show pending operations in the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -f -a "sync" -d 'Manually sync all pending operations'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -f -a "clear" -d 'Clear completed operations from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -f -a "remove" -d 'Remove a specific operation from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and not __fish_seen_subcommand_from status sync clear remove help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from sync" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from clear" -l all -d 'Clear all operations including pending'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from clear" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from clear" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from remove" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show pending operations in the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Manually sync all pending operations'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from help" -f -a "clear" -d 'Clear completed operations from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a specific operation from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand queue; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and not __fish_seen_subcommand_from add list help" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and not __fish_seen_subcommand_from add list help" -s h -l help -d 'Print help'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and not __fish_seen_subcommand_from add list help" -f -a "add" -d 'Add a comment to a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and not __fish_seen_subcommand_from add list help" -f -a "list" -d 'List comments on a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and not __fish_seen_subcommand_from add list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from add" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from help" -f -a "add" -d 'Add a comment to a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from help" -f -a "list" -d 'List comments on a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand comment; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand completions" -s v -l verbose -d 'Enable verbose debug output'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand completions" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "init" -d 'Initialize a new Oxen repository for a Logic Pro project'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "add" -d 'Stage changes to be committed'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "commit" -d 'Create a commit with optional audio metadata'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "log" -d 'Show commit history'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "restore" -d 'Restore project to a previous commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "status" -d 'Show repository status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "show" -d 'Show detailed information about a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "diff" -d 'Show changes between commits or working directory'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "compare" -d 'Compare metadata between two commits'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "search" -d 'Search commit history with advanced filtering'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "lock" -d 'Manage project locks for team collaboration'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "auth" -d 'Authenticate with Oxen Hub for remote collaboration'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "metadata-diff" -d 'Compare metadata between two Logic Pro project versions'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "daemon" -d 'Control the background daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "hooks" -d 'Manage workflow automation hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "console" -d 'Launch interactive console for real-time monitoring'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "activity" -d 'Show recent project activity timeline'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "team" -d 'Show team members and their contributions'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "queue" -d 'Manage offline operation queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "comment" -d 'Manage comments on commits'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "completions" -d 'Generate shell completion scripts'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and not __fish_seen_subcommand_from init add commit log restore status show diff compare search lock auth metadata-diff daemon hooks console activity team queue comment completions help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from lock" -f -a "acquire" -d 'Acquire exclusive lock for editing'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from lock" -f -a "release" -d 'Release the lock you currently hold'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from lock" -f -a "status" -d 'Show current lock status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from lock" -f -a "break" -d 'Force break an existing lock (admin only)'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "login" -d 'Login to Oxen Hub with API credentials'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "logout" -d 'Logout from Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "status" -d 'Show current authentication status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "test" -d 'Test authentication with Oxen Hub'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "status" -d 'Check daemon status'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "start" -d 'Start the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "stop" -d 'Stop the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "restart" -d 'Restart the daemon service'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "logs" -d 'Show daemon logs'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "init" -d 'Initialize hooks directory'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "list" -d 'List all installed hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "builtins" -d 'List available built-in hooks'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "install" -d 'Install a built-in hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "remove" -d 'Remove an installed hook'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from queue" -f -a "status" -d 'Show pending operations in the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from queue" -f -a "sync" -d 'Manually sync all pending operations'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from queue" -f -a "clear" -d 'Clear completed operations from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from queue" -f -a "remove" -d 'Remove a specific operation from the queue'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from comment" -f -a "add" -d 'Add a comment to a commit'
complete -c oxenvcs-cli -n "__fish_oxenvcs_cli_using_subcommand help; and __fish_seen_subcommand_from comment" -f -a "list" -d 'List comments on a commit'
